AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-wiki

  Sample SAM Template for sam-app-wiki

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  WikiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: wiki/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Wiki:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /wiki
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WikiApi:
    Description: "API Gateway endpoint URL for Prod stage for Wiki function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  WikiFunction:
    Description: "Wiki Lambda Function ARN"
    Value: !GetAtt WikiFunction.Arn
  WikiFunctionIamRole:
    Description: "Implicit IAM Role created for Wiki function"
    Value: !GetAtt WikiFunctionRole.Arn
