AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app-make-change

  Sample SAM Template for sam-app-make-change

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MakeChangeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: make_change/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        MakeChange:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /make_change
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MakeChangeApi:
    Description: "API Gateway endpoint URL for Prod stage for Make Change function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/make_change/"
  MakeChangeFunction:
    Description: "Make Change Lambda Function ARN"
    Value: !GetAtt MakeChangeFunction.Arn
  MakeChangeFunctionIamRole:
    Description: "Implicit IAM Role created for Make Change function"
    Value: !GetAtt MakeChangeFunctionRole.Arn
